[global]
   workgroup = WORKGROUP
   server string = myhome.server
   server role = standalone server
   security = user
   map to guest = never
   interfaces = lo eno1 wlo2
   bind interfaces only = yes
   hosts allow = 127. 192.168.30.
   hosts deny = 0.0.0.0/0
   min protocol = SMB2

[LanShare]
   comment = LAN SSD Share
   path = /srv/lan-share
   browseable = yes
   read only = no
   guest ok = no
   valid users = @familyshare
   force group = familyshare
   create mask = 0660
   directory mask = 2770
   inherit permissions = yes

[FileBackup]
   comment = Versioned File Backup on External Storage
   path = @STORAGE_ROOT@/file-backup
   browseable = yes
   read only = no
   guest ok = no
   valid users = @familyshare
   force group = familyshare
   create mask = 0660
   directory mask = 2770
   inherit permissions = yes
