services:
  kopia:
    image: kopia/kopia:0.22.3
    container_name: kopia
    hostname: home-server
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "51515:51515"
    command:
      - server
      - start
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=${KOPIA_SERVER_USERNAME}
      - --server-password=${KOPIA_SERVER_PASSWORD}
    environment:
      KOPIA_PASSWORD: ${KOPIA_PASSWORD}
      USER: ashton
      TZ: Asia/Hong_Kong
    volumes:
      - /opt/kopia/config:/app/config
      - /opt/kopia/cache:/app/cache
      - /opt/kopia/logs:/app/logs
      - ${STORAGE_ROOT}/file-backup:/data:ro
      - ${STORAGE_ROOT}/kopia-repository:/repository
