services:
  kopia:
    extends:
      file: ../kopia-common.yml
      service: kopia-common
    container_name: kopia
    ports:
      - "51515:51515"
    command:
      - server
      - start
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=${KOPIA_SERVER_USERNAME}
      - --server-password=${KOPIA_SERVER_PASSWORD}
    volumes:
      - /opt/kopia/config:/app/config
      - /opt/kopia/cache:/app/cache
      - /opt/kopia/logs:/app/logs
      - ${STORAGE_ROOT}/file-backup:/data:ro
      - ${STORAGE_ROOT}/kopia-repository:/repository
